---
version: 0.1

runson: ${matrix.os}
concurrency: 2

cypress: true
cypressOps:
  Build: "Hyperexecute Cypress Sample Build"
  Tags: ["HYP-Cypress", "macOS", "Matrix", "Accessibility"]
  BuildTags: ["HYP-Cypress-v9"]

pre:
  - npm install
  - npm install cypress@9.6.1 --save-dev
  - npm i lambdatest-cypress-cli

matrix:
   os: [mac]
   browser: ["chrome"]
   files: ["actions.spec.js", "aliasing.spec.js", "assertions.spec.js", "connectors.spec.js", "cookies.spec.js"]

testSuites: 
  - npx cypress run  --spec ./cypress/integration/$files --browser=$browser --headed --config video=true

parallelism: 1

jobLabel: [cypress-v9, mac, matrix]